### ISSUE TITLE
Import & Export of collection field

### ISSUE THREAD

**Issue by Ragers** [aprokopenko/justcustomfields#67]
Hi,

It seems that there might be a possible bug with the exporting and importing of json data on collection fields. It seems that it does not recursively collects all the field data for this field type when exporting it.
It just shows up as "Array", and no further details are given.

eg.
```
{
    "tours": {
        "fieldsets": {
            "itinerary": {
                "title": "Itinerary",
                "fields": {
                    "collection-1476715506": {
                        "title": "test",
                        "custom_row": "1",
                        "slug": "_test",
                        "enabled": "1",
                        "_version": "2.302",
                        "fields": "Array"
                    }
                }
            }
        }
    }
}
```
Thanks,
Hope you can push a quick fix for this item, or I can look at a fix for you if your interested.

**Comment by aprokopenko** [comment]
Thanks for the comment.
Actually we're very close to launch new v3.0 which are totally rebuild and all features rewritten and tested. We are preparing new site for our plugin. I hope it will be launched in 1 month.

So v2.3 is not supported anymore, because code is a bit outdated (procedural code style, which is hard to support).

You can download it from a v3_master branch here if you like to try it. However the json format for export/import is not compatible with v2.3. There are few different keys used inside the json.

**Comment by Ragers** [comment]
Awesome, thanks for the reply. I will test out your v3.0 for now.
