### ISSUE TITLE
Get the Label of a Field in Template Files

### ISSUE THREAD

**Issue by netzgestaltung** [aprokopenko/justcustomfields#88]
Hi - is there any chance to use field labels as frontend field labels as well?

when i look into /plugins/just-custom-fields/views/fieldsets/index.php - there is 

`$field_settings[$field_id]['title']`

inside a

`foreach($fieldset['fields'] as $field_id => $enabled)`

loop

greets, tom

**Comment by aprokopenko** [comment]
Hi,

You can copy some code from /plugins/just-custom-fields/models/Shortcodes to create a field object (this on is used to process [jcf-value] shortcode). 
Then from field object you can get `$field->instance['title']`.

However this method is not very optimal, because it foreach all fields settings every time to find the right field IDs. Of course if you find these IDs by yourself and hard-code them - than it will be much faster.

I recommend to store settings inside the theme (use plugin option to save settings to file system). Then it's easier to check field settings in usual json file.

**Comment by netzgestaltung** [comment]
```
ok so i will try to make a "get_jcf_field_label($field_id)" function at template.php

the current template code at es single.php


  
  <?php
    $post_meta = get_post_custom();
    $dates = unserialize($post_meta['_dates'][0]);
    $beginTime = $post_meta['_begin_time'][0];
    $entryTime = $post_meta['_entry_time'][0];
    $price = $post_meta['_price'][0];
  ?>

...

      <aside class="meta">
        <ul class="inner clearfix">
        <?php if ( !empty($dates) ) { ?>
	        <li class="dates">
	        <h3><?php echo __('Termine', 'sandbox'); ?></h3>
	        <ul>
	        <?php foreach ( $dates as $date ) { ?>
	          <li><?php echo date("j. n. Y", strtotime($date['_date'])); ?></li>
          <?php } ?>
          </ul>
        <?php } ?>
        <?php if ( !empty($beginTime) ) { ?>
	        <li class="beginTime"><?php echo __('Beginnzeit', 'sandbox'); ?>: <?php echo $beginTime; ?></li>
        <?php } ?>
        <?php if ( !empty($entryTime) ) { ?>
	        <li class="entryTime"><?php echo __('Einlass', 'sandbox'); ?>: <?php echo $entryTime; ?></li>
        <?php } ?>
        <?php if ( !empty($price) ) { ?>
	        <li class="price"><?php echo __('Preis', 'sandbox'); ?>: EUR <?php echo $price; ?>.-</li>
        <?php } ?>
        </ul>
      </aside>

so it should replace eg `echo __('Preis', 'sandbox');` with `echo get_jcf_field_label('_price');`.

i will post the code when i have it

**Comment by aprokopenko** [comment]
almost, except it's better to do something like this: 

`echo get_jcf_field_label('post', 'field_1234532');`  (first one is the current post type, second one is a real ID, you can find it inside json settings)

**Comment by netzgestaltung** [comment]
Haha - again having the same question ;-)
again i will stay with the text strings ;-)
